# Set the title of your multilabel archive
title: Cometa

# Set the maintainer name and email
maintainer:
  name: David Charte
  email: fdavidcl@protonmail.com

# Set the root of your site (without trailing slash) e.g. "", "/data"
baseurl: ""

# Advanced configuration. Edit only if you know what you're doing
permalink: pretty

data_gen:
  path: "datasets"
  dir: "datasets"

partitioning:
  strategy:
    - id: rand
      name: Random
    - id: stra
      name: Stratified
    - id: iter
      name: Iterative stratified
  validation:
    - id: hout
      name: Hold out
    - id: 2x5
      name: 2x5-fold cross validation
    - id: 1x10
      name: 10-fold cross validation
  format:
    - id: mulan
      name: MULAN
    - id: meka
      name: MEKA
    - id: libsvm
      name: LibSVM
    - id: keel
      name: KEEL
    - id: mldr
      name: mldr

dataset_metrics:
  - id:  "num.instances"
    name: Instances
  - id:  "num.attributes"
    name: Attributes
  - id:  "num.inputs"
    name: Inputs
  - id:  "num.labels"
    name: Labels
  - id:  "num.labelsets"
    name: Labelsets
  - id:  "num.single.labelsets"
    name: Single
  - id:  "max.frequency"
    name: Max freq
  - id:  "cardinality"
    name: Card
  - id:  "density"
    name: Dens
  - id:  "meanIR"
    name: Mean IR
  - id:  "scumble"
    name: Scumble
  - id:  "tcs"
    name: TCS

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Software attribution
developers:
  - Francisco Charte
  - David Charte

source_code: "https://github.com/fdavidcl/cometa"