# Set the title of your multilabel archive
title: Cometa

# Set the maintainer name and email
maintainer:
  name: David Charte
  email: fdavidcl@protonmail.com

# Enable or disable submission system
submission:
  enabled: false
  repo: "user/repo"
  token: "Paste a token from https://github.com/settings/tokens"


# Citation contents
citation:
  apa: "Charte, F., Rivera, A. J., Charte, D., del Jesus, M. J., & Herrera, F. (2018). Tips, guidelines and tools for managing multi-label datasets: the mldr. datasets R package and the Cometa data repository. Neurocomputing."
  bibtex: >
    @article{cometaml,
      title = "Tips, guidelines and tools for managing multi-label datasets: The mldr.datasets R package and the Cometa data repository",
      journal = "Neurocomputing",
      year = "2018",
      issn = "0925-2312",
      doi = "https://doi.org/10.1016/j.neucom.2018.02.011",
      author = "Francisco Charte and Antonio J. Rivera and David Charte and María J. del Jesus and Francisco Herrera"
    }

# Set the root of your site (without trailing slash) e.g. "", "/data"
baseurl: ""

# Choose an accent color. It can be any CSS color(e.g. #0080b0) or
# a variable defined by Bulma https://bulma.io/documentation/overview/colors/
accent: "#4c3470"

# Advanced configuration. Edit only if you know what you're doing
permalink: pretty

data_gen:
  path: "datasets"
  dir: "datasets"

partitioning:
  strategy:
    - id: rand
      name: Random
    - id: stra
      name: Stratified
    - id: iter
      name: Iterative stratified
  validation:
    - id: hout
      name: Hold out
    - id: 2x5
      name: 2x5-fold cross validation
    - id: 1x10
      name: 10-fold cross validation
  format:
    - id: mulan
      name: MULAN
    - id: meka
      name: MEKA
    - id: libsvm
      name: LibSVM
    - id: keel
      name: KEEL
    - id: mldr
      name: mldr

dataset_metrics:
  - id:  "num.instances"
    name: Instances
  - id:  "num.attributes"
    name: Attributes
  - id:  "num.inputs"
    name: Inputs
  - id:  "num.labels"
    name: Labels
  - id:  "num.labelsets"
    name: Labelsets
  - id:  "num.single.labelsets"
    name: Single
  - id:  "max.frequency"
    name: Max freq
  - id:  "cardinality"
    name: Card
  - id:  "density"
    name: Dens
  - id:  "meanIR"
    name: Mean IR
  - id:  "scumble"
    name: Scumble
  - id:  "tcs"
    name: TCS

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Software attribution
developers:
  - Francisco Charte
  - Antonio J. Rivera
  - David Charte

software:
  name: Cometa
  source: "https://github.com/fdavidcl/cometa"
